### ISSUE TITLE
Add support for IfXTable and Counter64

### ISSUE THREAD

**Issue by enmaskarado** [troglobit/mini-snmpd#3]
Hello
Well, I thought that this project had disappeared ... It's really great news that is not. Thank you for continuing to maintain the program.

I have mini_snmpd running on a router: my problem is that statistics do not work well when I use this router to its maximum capacity; network counters (ifOutOctets, ifInOctets) currently work with Counter32, and it overflows.

In OpenWrt there is a patch (https://dev.openwrt.org/ticket/13597) for the old version, 2b, which implements Counter64. I tried to rebase the patch but it is very difficult to do for me.

Is possible to implement Counter64 support in the project?

Regards!

**Comment by troglobit** [comment]
Hi @maverickp, great of you to try and port the patch!  Unfortunately, like you've noticed, there's been quite a lot of changes in the projects since that 64-bit patch was first created.

I'm afraid I personally do not have time to forward port the patch, or re-implement it, currently. Family and work comes first, then when I get the itch I do try to keep up with my many projects.  But even then, mini-snmpd is not a top priority project for me atm.

Anyway, useful information about how to transition form 32-bit to 64-bit counters is documented here https://tools.ietf.org/html/rfc2863 -- whenever someone gets to this.

Thank you for the report!

**Comment by maverickp** [comment]
Thanks for answering.
For my part I will try to solve this, and if I have news, I will come again.
Regards!

**Comment by hojuruku** [comment]
@maverickp I'm packaging this for openwrt now, with new init script / makefile. If you get the patch working let me know. I noticed mib.c changed a fair bit since 2.b too.

Most people will just have <10 sec/shorter refresh intervals so it shouldn't matter.
What throughput at what interval overflows the counters?

**Comment by hojuruku** [comment]
Isn't counter64 support part of the SNMPv2c spec?

**Comment by troglobit** [comment]
When preparing the v1.4 release, just now, I looked into this issue some more.

What needs to be done is to add base Counter64 support as well as adding the IfXTable, which uses Counter64.  The OpenWRT patch referenced above (now attached) modifies the IfTable to use Counter64, which works but is not the correct fix.

**Comment by jsalatiel** [comment]
Has this patch been commited to master ?

**Comment by troglobit** [comment]
@jsalatiel Nope, issue still very much alive. The referenced patch does not apply clean any more and should instead be implemented as a standard ifXTable.

**Comment by troglobit** [comment]
@inste Cool, this doesn't seem to be too complicated to merge!  Care to prepare a pull request?

(I'm quite busy with other projects at the moment, so it'll likely be a couple of months before I get back to actively working on this project.  But I'll happily audit code and merge pull requests.)

**Comment by inste** [comment]
@troglobit maybe I'll provide PR for vanilla version, as I know sources well, but don't promise anything.

**Comment by troglobit** [comment]
@inste Thanks for the heads-up, I noticed :)

It would be really great if you could give it a go, cheers!

**Comment by troglobit** [comment]
Fixed in 54e5cee, ported from NDM Systems fork. Took a while to get back to this, thanks @inste :-)
